version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mudumbai_db
      SPRING_DATASOURCE_USERNAME: mudumbai
      SPRING_DATASOURCE_PASSWORD: Connect@1


  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mudumbai_db
      POSTGRES_USER: mudumbai
      POSTGRES_PASSWORD: Connect@1
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: Connect@1
    ports:
      - "5050:80"

volumes:
  db_data:
